/** @type {import('stylelint').Config} */
export default {
  extends: ["stylelint-config-standard"],
  ignoreFiles: [
    "**/*.generated.css",
    "theme/rofi/**",
    "node_modules/**",
  ],
  rules: {
    // Waybar / cyberpunk theme uses free-form class and custom-property names.
    "selector-class-pattern": null,
    "selector-id-pattern": null,
    "custom-property-pattern": null,
    // Cascading theme sheets intentionally override earlier rules.
    "no-descending-specificity": null,
    // Prefer existing authored notation over mass rewrites.
    "color-function-notation": null,
    "color-function-alias-notation": null,
    "color-hex-length": null,
    "alpha-value-notation": null,
    "hue-degree-notation": null,
    "lightness-notation": null,
    "import-notation": null,
    "media-feature-range-notation": null,
    "declaration-block-no-redundant-longhand-properties": null,
    "declaration-block-single-line-max-declarations": null,
    "rule-empty-line-before": null,
    "comment-empty-line-before": null,
    "custom-property-empty-line-before": null,
    "declaration-empty-line-before": null,
    "at-rule-empty-line-before": null,
    "number-max-precision": null,
    // GTK3 / Waybar: invalid GtkCssProvider property names crash Waybar on load.
    // Mirror scripts/ci/check-gtk-css.sh (see https://docs.gtk.org/gtk3/css-properties.html).
    "property-disallowed-list": [
      "font-variant-ligatures",
      "font-variant-numeric",
      "font-feature-settings",
      "backdrop-filter",
      "filter",
      "transform",
      "width",
      "height",
      "max-width",
      "max-height",
      "overflow",
      "overflow-x",
      "overflow-y",
      "text-overflow",
      "display",
      "flex",
      "gap",
      "position",
      "z-index",
      "line-height",
      "white-space",
      "text-align",
      "box-sizing",
      "cursor",
    ],
  },
};
