name: Actionlint

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint and audit workflows
    permissions:
      contents: read
      security-events: write
    uses: bolens/.github/.github/workflows/reusable-actionlint.yml@d30ff6a56b47317d3d565e7b4747d133966db8d2
    with:
      security-audit: true
