name: Actionlint

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actionlint:
    name: Lint and audit workflows
    permissions:
      contents: read
    uses: bolens/.github/.github/workflows/reusable-actionlint.yml@3f2e5f3e61c419f3678ea8f472d24562254624c6
    with:
      security-audit: true
